module.exports = {
  content: ['./pages/**/*.{ts,tsx}', './src/**/*.{js,jsx,ts,tsx,mdx}'],
  theme: {
    extend: {},
    fontFamily: {
      sans: ['Noto Sans', 'sans-serif']
    },
    fontSize: {
      'base': '16px',
      'hero': ['3.75rem', { lineHeight: '5rem', letterSpacing: '0', fontWeight: '400' }],
      'hero-strong': ['3.75rem', { lineHeight: '4.125rem', letterSpacing: '0', fontWeight: '700' }],
      'headings-lg-light': ['2.5rem', { lineHeight: '3.75rem', letterSpacing: '0', fontWeight: '300' }],
      'headings-lg': ['2.5rem', { lineHeight: '3.75rem', letterSpacing: '0', fontWeight: '500' }],
      'headings-lg-strong': ['2.5rem', { lineHeight: '3.75rem', letterSpacing: '0', fontWeight: '700' }],
      'headings-xxl-light': ['2rem', { lineHeight: '3rem', letterSpacing: '0', fontWeight: '300' }],
      'headings-xxl': ['2rem', { lineHeight: '3rem', letterSpacing: '0', fontWeight: '500' }],
      'headings-xxl-strong': ['2rem', { lineHeight: '3rem', letterSpacing: '0', fontWeight: '700' }],
      'headings-xl-light': ['1.5rem', { lineHeight: '2.25rem', letterSpacing: '0', fontWeight: '300' }],
      'headings-xl': ['1.5rem', { lineHeight: '2.25rem', letterSpacing: '0', fontWeight: '500' }],
      'headings-xl-strong': ['1.5rem', { lineHeight: '2.25rem', letterSpacing: '0', fontWeight: '700' }],
      'headings-l': ['1.25rem', { lineHeight: '2rem', letterSpacing: '0', fontWeight: '400' }],
      'headings-l-strong': ['1.25rem', { lineHeight: '2rem', letterSpacing: '0', fontWeight: '700' }],
      'headings-m': ['1rem', { lineHeight: '1.75rem', letterSpacing: '0', fontWeight: '400' }],
      'headings-m-strong': ['1rem', { lineHeight: '1.75rem', letterSpacing: '0', fontWeight: '700' }],
      'headings-s': ['0.875rem', { lineHeight: '1.5rem', letterSpacing: '0', fontWeight: '400' }],
      'headings-s-strong': ['0.875rem', { lineHeight: '1.5rem', letterSpacing: '0', fontWeight: '700' }],
      'sub-headings-lg': ['1.375rem', { lineHeight: '2rem', letterSpacing: '0', fontWeight: '400' }],
      'sub-headings-lg-strong': ['1.375rem', { lineHeight: '2rem', letterSpacing: '0', fontWeight: '700' }],
      'sub-headings-xxl': ['1.25rem', { lineHeight: '2rem', letterSpacing: '0', fontWeight: '400' }],
      'sub-headings-xxl-strong': ['1.25rem', { lineHeight: '2rem', letterSpacing: '0', fontWeight: '700' }],
      'sub-headings-xl': ['1.125rem', { lineHeight: '2rem', letterSpacing: '0', fontWeight: '400' }],
      'sub-headings-xl-strong': ['1.125rem', { lineHeight: '2rem', letterSpacing: '0', fontWeight: '700' }],
      'sub-headings-l': ['1rem', { lineHeight: '1.75rem', letterSpacing: '0', fontWeight: '400' }],
      'sub-headings-l-strong': ['1rem', { lineHeight: '1.75rem', letterSpacing: '0', fontWeight: '700' }],
      'text-lg': ['2.5rem', { lineHeight: '3.25rem', letterSpacing: '0', fontWeight: '300' }],
      'text-lg-strong': ['2.5rem', { lineHeight: '3.25rem', letterSpacing: '0', fontWeight: '700' }],
      'text-xxl': ['2rem', { lineHeight: '3rem', letterSpacing: '0', fontWeight: '300' }],
      'text-xxl-strong': ['2rem', { lineHeight: '3rem', letterSpacing: '0', fontWeight: '700' }],
      'text-xl': ['1.5rem', { lineHeight: '2.25rem', letterSpacing: '0', fontWeight: '300' }],
      'text-xl-strong': ['1.5rem', { lineHeight: '2.25rem', letterSpacing: '0', fontWeight: '700' }],
      'text-l': ['1.25rem', { lineHeight: '3.25rem', letterSpacing: '0', fontWeight: '400' }],
      'text-l-strong': ['1.25rem', { lineHeight: '3.25rem', letterSpacing: '0', fontWeight: '700' }],
      'text-m': ['1rem', { lineHeight: '1.75rem', letterSpacing: '0', fontWeight: '400' }],
      'text-m-strong': ['1rem', { lineHeight: '1.75rem', letterSpacing: '0', fontWeight: '700' }],
      'text-s': ['0.875rem', { lineHeight: '1.5rem', letterSpacing: '0', fontWeight: '400' }],
      'text-s-strong': ['0.875rem', { lineHeight: '1.5rem', letterSpacing: '0', fontWeight: '700' }],
      'interaction-button-l': ['1.125rem', { lineHeight: '1.375rem', letterSpacing: '0', fontWeight: '500' }],
      'interaction-button-m': ['1rem', { lineHeight: '1.25rem', letterSpacing: '0', fontWeight: '500' }],
      'interaction-button-s': ['0.875rem', { lineHeight: '1.125rem', letterSpacing: '0', fontWeight: '500' }],
      'interaction-button-tab': ['0.875rem', { lineHeight: '1.125rem', letterSpacing: '0', fontWeight: '500' }],
      'interaction-input-label': ['1rem', { lineHeight: '1.25rem', letterSpacing: '0', fontWeight: '500' }],
      'interaction-input-text': ['1rem', { lineHeight: '1.25rem', letterSpacing: '0', fontWeight: '500' }]
    }
  },
  plugins: []
};
